# Generated by Django 2.2.7 on 2019-11-20 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20191120_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='coord_x',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='coord_y',
            new_name='y',
        ),
    ]
